<?php

/**
 * @file
 * Contains acquia_webinar_scrape.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function acquia_webinar_scrape_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the acquia_webinar_scrape module.
    case 'help.page.acquia_webinar_scrape':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Accquia Webinar scraping module using 3rd party library Goutte.') . '</p>';
      return $output;

    default:
  }
}
